project:
  type: website
  output-dir: docs
resources:
    - files/CV_Nesslage.pdf
website:
  title: "Jacob Nesslage"
  navbar:
    background: "#2C7FB8" # aquatic blue navbar
    foreground: "#FFFFFF"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: pubs.qmd
      - text: "CV"
        href: files/CV_Nesslage.pdf
  page-footer:
    background: "#D9EDF7"
    foreground: "#31708F"
    left:  "© 2025, Jacob Nesslage"
    right: Built using [GitHub](https://github.com/jollygoodjacob), [R](https://www.r-project.org/), and [Quarto](https://quarto.org/).

      

format:
  html:
    bibliography: scholar.bib
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true


editor: visual

