project:
  type: website
  output-dir: docs

website:
  title: "Jacob Nesslage, EIT"
  navbar:
    background: "#2C7FB8" # aquatic blue navbar
    foreground: "#FFFFFF"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: pubs.qmd
      - text: "CV"
        #href: cv.qmd
  page-footer:
    background: "#D9EDF7"
    foreground: "#31708F"
    left:  "© 2025, Jacob Nesslage"
    right: Built using [GitHub](https://github.com/jollygoodjacob), [R](https://www.r-project.org/), and [Quarto](https://quarto.org/).

      

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true


editor: visual

