project:
  type: website
  output-dir: docs

website:
  title: "Jacob Nesslage"
  navbar:
    background: "#f7cd46" # aquatic blue navbar
    foreground: "#5ac3b0"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: pubs.qmd
      - text: "CV"
        #href: cv.qmd
  page-footer:
    background: "#de5935"
    foreground: "#5ac3b0"
    left:  "© 2025, Jacob Nesslage"
    right: Built using [GitHub](https://github.com/jollygoodjacob), [R](https://www.r-project.org/), and [Quarto](https://quarto.org/).

      

format:
  html:
    bibliography: scholar.bib
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true


editor: visual

